### ISSUE TITLE
UX / UI review for Component - Toast Messages

### ISSUE THREAD

**Issue by nazlikaya** [camunda-cloud/common-ui#26]
Tested in integration stage.

- [ ] Toast disappears  Fade Out:
Duration: 300ms
Timing: ease-in-out
Currently, it is sliding to the bottom.

- [ ] While a modal window is open, the toast messages timer will be paused. After modal is closed, the timer continues.

- [x] The color of the X icon should be #62626e

- [ ] The message text length can up to 226px. I guess currently it is 224px.

- [ ] It is really small but, please revisit horizontal alignment and height of the modal when there are multiple lines. (Title needs to go up 1px, description text should have more distance from the title and more space under it etc.)
![Screenshot 2020-11-13 at 16 30 54](https://user-images.githubusercontent.com/16151298/99089494-add6f000-25cd-11eb-8ff0-b2a05e0039a7.png)

**Comment by alexandertrefz** [comment]
This issue is resolved with the Design Refactor of the Notifications.
