### ISSUE TITLE
Create new component  - Cards

### ISSUE THREAD

**Issue by nazlikaya** [camunda-cloud/common-ui#29]
We need to have a card component for different occasion in Console.

Here is the different states, design variations and description how a card should look like.
[Zeplin Component - Cards](https://zpl.io/VDPwENJ)

The places currently we need to use the card are user settings, "Modeler for Desktop" and "Sample projects for Github" cards in Diagrams tab and graphs in metrics tab.

Please check it out and if you have concerns, let's discuss.

**Comment by alexandertrefz** [comment]
The descriptions in Zeplin are in contradiction with each other.

At one point you are showing that all 3 areas should have 40px padding from the right, but then show various cards with buttons and toggles that have significantly less padding to the right.

The notion of card sizes also doesnt make any sense. It has recently changed from fixed pixel sizes (which make no sense at all) to "small" and "large" - but these are just making the card wider or narrower, something the card doesnt need any control over - this is a layout concern, that should be handled by the application, not common-ui, just like the "nesting" you display in the picture above.

**Comment by nazlikaya** [comment]
@alexandertrefz, thanks for the feedback.

> At one point you are showing that all 3 areas should have 40px padding from the right, but then show various cards with buttons and toggles that have significantly less padding to the right.

I have revisited each content and updated them.

> The notion of card sizes also doesnt make any sense. It has recently changed from fixed pixel sizes (which make no sense at all) to "small" and "large" - but these are just making the card wider or narrower, something the card doesnt need any control over - this is a layout concern, that should be handled by the application, not common-ui, just like the "nesting" you display in the picture above.

I have deleted the term small and large, but put a comment in the description that card can have 2 different width sizes.

I have created this screenshots or documentation not only for common-ui but also for other developers and maybe even OPE team, so it is a general doc that I provide everyone who is related.

Other than that if something is not related with common-ui, you can simply ignore the information (such as layout). Unfortunately, I do not have the knowledge of which part should be in the library and which part should be handled in console part.
