### ISSUE TITLE
Font loading from Google fonts should be optional

### ISSUE THREAD

**Issue by dlavrenuek** [camunda-cloud/common-ui#32]
## Description
When using the `common-ui` loaded the IBM-Flex font from Google fonts cdn is hardcoded in [style.css](https://github.com/camunda-cloud/common-ui/blob/master/src/global/style.css#L1) even if it is self-hosted by the application. This is the case for [`iam frontend`](https://github.com/camunda/iam/tree/master/frontend). As far as I know, using external resources also requires adding the provider to privacy policy.

## Solution
Loading the fonts from external resources should not be included in the default `style.css` but use another file for this purpose.

**Comment by alexandertrefz** [comment]
Stencil only permits a single global CSS file, and as this required an explanation in the Docs anyway, I simply removed the font loading.

**Comment by dlavrenuek** [comment]
@alexandertrefz thanks a lot 👍
