### ISSUE TITLE
Input fields validation result error message should match application language

### ISSUE THREAD

**Issue by dlavrenuek** [camunda-cloud/common-ui#87]
At the moment the validation messages f.e. for a `<CmTextfield required />` will match the user's browser language even if it is not supported by the application. This is especially disturbing when backend validation is used resulting in some error messages being in a wrong language. The only option right now to have consistent behavior is not to use common-ui validation at all.

Example common ui validation
<img width="652" alt="Bildschirmfoto 2021-12-14 um 16 12 30" src="https://user-images.githubusercontent.com/20122620/146025382-3206282b-ced6-43a7-8de9-f3fc197247e5.png">

Example application specific error message
<img width="644" alt="Bildschirmfoto 2021-12-14 um 16 12 50" src="https://user-images.githubusercontent.com/20122620/146025380-a053ac16-ea07-462b-9137-b47b5a9f4e4f.png">

**Comment by alexandertrefz** [comment]
This is browser level behaviour. If you want to opt out of the browser validation, you can do so by using the `ignoreDefaultValidation` property on the `validation` object. That turns off all default validation, and with it, all browser level error messages as they are created by said validation.

This is to be cautioned against, as this creates inconsistent error messages (for example for required fields), as well as opening yourself up to many implementation mistakes in the validation itself, as you then have to handle `required`, etc yourself.

**Comment by dlavrenuek** [comment]
Thank you for the hint with `ignoreDefaultValidation`

> as well as opening yourself up to many implementation mistakes in the validation itself, as you then have to handle required, etc yourself.

I can not imagine that any of the Camunda applications rely only on client side validation, so we can assume that the validation will always be correctly implemented.
